address = "127.0.0.1"
port = 3000
secret = ""
dev_secret = ""
dev_routes = ["/v2/player"]
exposed_secret = ""
exposed_routes = ["/v2/patreon", "/v2/patreon/patrons", "/v2/discord/user", "/v2/discord/member"]
cli_colors = true
log_level = "normal"

[discord]
token = ""
guild = 0
patreon_role = 0

[database]
user = "root"
password = ""
host = "127.0.0.1"
port = 3306
database = ""

[proxy]
discord = "discord.com"
token = ""

[[servers]]
name = "Primary Station"
address = "127.0.0.1:1337"
connection_address = "12.34.567.89:1337"
error_message = "Rebooting"

[[servers]]
name = "Secondary Station"
address = "127.0.0.1:7331"
connection_address = "98.76.543.2.1:7331"
error_message = "Rebooting"
